vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /images/pins
            upload_destination: '%kernel.project_dir%/public/images/pins'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
